name: Asan

on:
  pull_request:
    branches:
      - stable
      - unstable
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  pre_job:
    # continue-on-error: true # Uncomment once integration is finished
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@master
        with:
          # All of these options are optional, so you can remove them if you are happy with the defaults
          cancel_others: 'true'
          do_not_skip: '["pull_request", "workflow_dispatch", "schedule"]'
  build:
    name: Asan
    needs: pre_job
    if: ${{ needs.pre_job.outputs.should_skip != 'true' }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          submodules: false

      - uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install dependencies on ubuntu
        run: |
          sudo apt-get update
          sudo apt-get install -y valgrind

      - name: Install python packages
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install --upgrade pybind11 cmake ninja pytest

          
      - name: Configure
        run: |
          cmake -S . -G Ninja -B build \
              -DCMAKE_BUILD_TYPE=Debug \
              -DDIPTEST_ENABLE_DEBUG=OFF \
              -DDIPTEST_ENABLE_OPENMP=ON \
              -Dpybind11_DIR=$(python3 -c 'import pybind11; print(pybind11.get_cmake_dir())') \
              -DCMAKE_C_COMPILER=clang-11 \
              -DCMAKE_CXX_COMPILER=clang++-11 \
              -DCMAKE_INSTALL_PREFIX:PATH=. \
              -DCMAKE_BUILD_TYPE=Asan \
              -DLDFLAGS=-shared-libasan

      - name: Build
        run: |
          cmake --build build \
          --target install \
          --config Asan

      - name: Install packages
        run: |
          DIPTEST_MANUAL_BUILD=ON python -m pip install -e . -v

      - name: Test
        run: |
          LD_PRELOAD=$(clang -print-file-name=libclang_rt.asan-x86_64.so) \
          ASAN_OPTIONS=detect_leaks=0 \
          PYTHONMALLOC=malloc \
          python -m pytest tests/test_diptest.py
